/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TChainNode;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TChainNodeRecord extends UpdatableRecordImpl<TChainNodeRecord> implements Record9<Long, String, String, String, String, String, String, Long, Long> {

    private static final long serialVersionUID = 1892432565;

    /**
     * Setter for <code>asimov_server.t_chain_node.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.ip</code>. IP
     */
    public void setIp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.ip</code>. IP
     */
    public String getIp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.city</code>. 城市
     */
    public void setCity(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.city</code>. 城市
     */
    public String getCity() {
        return (String) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.subdivision</code>. 省份
     */
    public void setSubdivision(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.subdivision</code>. 省份
     */
    public String getSubdivision() {
        return (String) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.country</code>. 国家
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.country</code>. 国家
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.longitude</code>. 经度
     */
    public void setLongitude(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.longitude</code>. 经度
     */
    public String getLongitude() {
        return (String) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.latitude</code>. 纬度
     */
    public void setLatitude(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.latitude</code>. 纬度
     */
    public String getLatitude() {
        return (String) get(6);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>asimov_server.t_chain_node.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>asimov_server.t_chain_node.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, String, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, String, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TChainNode.T_CHAIN_NODE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TChainNode.T_CHAIN_NODE.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TChainNode.T_CHAIN_NODE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TChainNode.T_CHAIN_NODE.SUBDIVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TChainNode.T_CHAIN_NODE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TChainNode.T_CHAIN_NODE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TChainNode.T_CHAIN_NODE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TChainNode.T_CHAIN_NODE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TChainNode.T_CHAIN_NODE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSubdivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSubdivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value2(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value3(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value4(String value) {
        setSubdivision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value5(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value6(String value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value7(String value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value8(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord value9(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChainNodeRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TChainNodeRecord
     */
    public TChainNodeRecord() {
        super(TChainNode.T_CHAIN_NODE);
    }

    /**
     * Create a detached, initialised TChainNodeRecord
     */
    public TChainNodeRecord(Long id, String ip, String city, String subdivision, String country, String longitude, String latitude, Long createTime, Long updateTime) {
        super(TChainNode.T_CHAIN_NODE);

        set(0, id);
        set(1, ip);
        set(2, city);
        set(3, subdivision);
        set(4, country);
        set(5, longitude);
        set(6, latitude);
        set(7, createTime);
        set(8, updateTime);
    }
}
