/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TDaoAsset;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoAssetRecord extends UpdatableRecordImpl<TDaoAssetRecord> implements Record11<Long, String, String, String, String, String, String, String, Byte, Long, Long> {

    private static final long serialVersionUID = 1622428414;

    /**
     * Setter for <code>asimov_server.t_dao_asset.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.tx_hash</code>. 交易Hash
     */
    public void setTxHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.tx_hash</code>. 交易Hash
     */
    public String getTxHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.contract_address</code>. 组织合约地址
     */
    public void setContractAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.contract_address</code>. 组织合约地址
     */
    public String getContractAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.asset</code>. 资产ID
     */
    public void setAsset(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.asset</code>. 资产ID
     */
    public String getAsset() {
        return (String) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.name</code>. 资产名称
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.name</code>. 资产名称
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.symbol</code>. 资产symbol
     */
    public void setSymbol(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.symbol</code>. 资产symbol
     */
    public String getSymbol() {
        return (String) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.description</code>. 资产描述
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.description</code>. 资产描述
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.logo</code>. 资产logo
     */
    public void setLogo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.logo</code>. 资产logo
     */
    public String getLogo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.asset_status</code>. 资产状态，0-初始化，待投票通过，1-发行成功，2-发行失败
     */
    public void setAssetStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.asset_status</code>. 资产状态，0-初始化，待投票通过，1-发行成功，2-发行失败
     */
    public Byte getAssetStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>asimov_server.t_dao_asset.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_asset.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, String, String, String, String, Byte, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, String, String, String, String, String, String, Byte, Long, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDaoAsset.T_DAO_ASSET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDaoAsset.T_DAO_ASSET.TX_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDaoAsset.T_DAO_ASSET.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TDaoAsset.T_DAO_ASSET.ASSET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TDaoAsset.T_DAO_ASSET.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TDaoAsset.T_DAO_ASSET.SYMBOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TDaoAsset.T_DAO_ASSET.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TDaoAsset.T_DAO_ASSET.LOGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return TDaoAsset.T_DAO_ASSET.ASSET_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TDaoAsset.T_DAO_ASSET.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return TDaoAsset.T_DAO_ASSET.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getAssetStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAsset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLogo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getAssetStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value2(String value) {
        setTxHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value3(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value4(String value) {
        setAsset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value6(String value) {
        setSymbol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value8(String value) {
        setLogo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value9(Byte value) {
        setAssetStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value10(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord value11(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAssetRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, Byte value9, Long value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDaoAssetRecord
     */
    public TDaoAssetRecord() {
        super(TDaoAsset.T_DAO_ASSET);
    }

    /**
     * Create a detached, initialised TDaoAssetRecord
     */
    public TDaoAssetRecord(Long id, String txHash, String contractAddress, String asset, String name, String symbol, String description, String logo, Byte assetStatus, Long createTime, Long updateTime) {
        super(TDaoAsset.T_DAO_ASSET);

        set(0, id);
        set(1, txHash);
        set(2, contractAddress);
        set(3, asset);
        set(4, name);
        set(5, symbol);
        set(6, description);
        set(7, logo);
        set(8, assetStatus);
        set(9, createTime);
        set(10, updateTime);
    }
}
