/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TDaoAccount;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoAccountRecord extends UpdatableRecordImpl<TDaoAccountRecord> implements Record6<Long, String, String, String, Long, Long> {

    private static final long serialVersionUID = 684201812;

    /**
     * Setter for <code>asimov_server.t_dao_account.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_dao_account.address</code>. 地址
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_dao_account.nick_name</code>. 昵称
     */
    public void setNickName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.nick_name</code>. 昵称
     */
    public String getNickName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_dao_account.avatar</code>. 头像
     */
    public void setAvatar(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.avatar</code>. 头像
     */
    public String getAvatar() {
        return (String) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_dao_account.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_dao_account.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_account.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDaoAccount.T_DAO_ACCOUNT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDaoAccount.T_DAO_ACCOUNT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDaoAccount.T_DAO_ACCOUNT.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TDaoAccount.T_DAO_ACCOUNT.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TDaoAccount.T_DAO_ACCOUNT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return TDaoAccount.T_DAO_ACCOUNT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value3(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value4(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value5(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord value6(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAccountRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDaoAccountRecord
     */
    public TDaoAccountRecord() {
        super(TDaoAccount.T_DAO_ACCOUNT);
    }

    /**
     * Create a detached, initialised TDaoAccountRecord
     */
    public TDaoAccountRecord(Long id, String address, String nickName, String avatar, Long createTime, Long updateTime) {
        super(TDaoAccount.T_DAO_ACCOUNT);

        set(0, id);
        set(1, address);
        set(2, nickName);
        set(3, avatar);
        set(4, createTime);
        set(5, updateTime);
    }
}
