/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TDaoMessage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoMessageRecord extends UpdatableRecordImpl<TDaoMessageRecord> implements Record10<Long, Integer, Integer, Integer, String, String, String, Integer, Long, Long> {

    private static final long serialVersionUID = 2069336473;

    /**
     * Setter for <code>asimov_server.t_dao_message.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.category</code>. 消息分类：1：成为组织的普通成员，2：组织有新成员加入，3：成功创建组织，4：成员被从组织中移除，5：组织中移除了成员，6：成为组织新主席，7：主席换人，8：财务支出，9：发行资产，10：修改组织logo，11：修改组织名称，12：收到投票消息，13：提议投票未通过，14：提议到期，15：被邀请进入组织，16：关闭组织，17：组织收到资产 18：组织增发资产
     */
    public void setCategory(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.category</code>. 消息分类：1：成为组织的普通成员，2：组织有新成员加入，3：成功创建组织，4：成员被从组织中移除，5：组织中移除了成员，6：成为组织新主席，7：主席换人，8：财务支出，9：发行资产，10：修改组织logo，11：修改组织名称，12：收到投票消息，13：提议投票未通过，14：提议到期，15：被邀请进入组织，16：关闭组织，17：组织收到资产 18：组织增发资产
     */
    public Integer getCategory() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.type</code>. 消息类型：0-只读消息,1-直接执行,2-投票
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.type</code>. 消息类型：0-只读消息,1-直接执行,2-投票
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.message_position</code>. 消息适用范围：0、官网，1、DAO组织，2、两者皆有
     */
    public void setMessagePosition(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.message_position</code>. 消息适用范围：0、官网，1、DAO组织，2、两者皆有
     */
    public Integer getMessagePosition() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.contract_address</code>. 组织合约地址
     */
    public void setContractAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.contract_address</code>. 组织合约地址
     */
    public String getContractAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.receiver</code>. 消息接受人地址
     */
    public void setReceiver(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.receiver</code>. 消息接受人地址
     */
    public String getReceiver() {
        return (String) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.additional_info</code>. 附加信息(JSON字符串)
     */
    public void setAdditionalInfo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.additional_info</code>. 附加信息(JSON字符串)
     */
    public String getAdditionalInfo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.state</code>. 消息状态：0-未读，1-已读, 2-已拒绝，3-已同意
     */
    public void setState(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.state</code>. 消息状态：0-未读，1-已读, 2-已拒绝，3-已同意
     */
    public Integer getState() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>asimov_server.t_dao_message.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_message.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, Integer, Integer, String, String, String, Integer, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Integer, Integer, Integer, String, String, String, Integer, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDaoMessage.T_DAO_MESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TDaoMessage.T_DAO_MESSAGE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TDaoMessage.T_DAO_MESSAGE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TDaoMessage.T_DAO_MESSAGE.MESSAGE_POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TDaoMessage.T_DAO_MESSAGE.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TDaoMessage.T_DAO_MESSAGE.RECEIVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TDaoMessage.T_DAO_MESSAGE.ADDITIONAL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TDaoMessage.T_DAO_MESSAGE.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TDaoMessage.T_DAO_MESSAGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TDaoMessage.T_DAO_MESSAGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMessagePosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMessagePosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReceiver();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value2(Integer value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value3(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value4(Integer value) {
        setMessagePosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value5(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value6(String value) {
        setReceiver(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value7(String value) {
        setAdditionalInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value8(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value9(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord value10(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoMessageRecord values(Long value1, Integer value2, Integer value3, Integer value4, String value5, String value6, String value7, Integer value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDaoMessageRecord
     */
    public TDaoMessageRecord() {
        super(TDaoMessage.T_DAO_MESSAGE);
    }

    /**
     * Create a detached, initialised TDaoMessageRecord
     */
    public TDaoMessageRecord(Long id, Integer category, Integer type, Integer messagePosition, String contractAddress, String receiver, String additionalInfo, Integer state, Long createTime, Long updateTime) {
        super(TDaoMessage.T_DAO_MESSAGE);

        set(0, id);
        set(1, category);
        set(2, type);
        set(3, messagePosition);
        set(4, contractAddress);
        set(5, receiver);
        set(6, additionalInfo);
        set(7, state);
        set(8, createTime);
        set(9, updateTime);
    }
}
