/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TDaoOperation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoOperationRecord extends UpdatableRecordImpl<TDaoOperationRecord> implements Record9<Long, String, String, Byte, String, Byte, String, Long, Long> {

    private static final long serialVersionUID = -198916608;

    /**
     * Setter for <code>asimov_server.t_dao_operation.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.tx_hash</code>. 交易Hash
     */
    public void setTxHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.tx_hash</code>. 交易Hash
     */
    public String getTxHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.contract_address</code>. 组织合约地址
     */
    public void setContractAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.contract_address</code>. 组织合约地址
     */
    public String getContractAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.operation_type</code>. 操作类型：1、创建组织 2、关闭组织 3、修改组织名 4、移除成员 5、创建资产 6、转移资产 7、转让主席 8、确认主席 9、邀请成员 10、加入组织 11、投票 12、修改组织logo 13、增发资产
     */
    public void setOperationType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.operation_type</code>. 操作类型：1、创建组织 2、关闭组织 3、修改组织名 4、移除成员 5、创建资产 6、转移资产 7、转让主席 8、确认主席 9、邀请成员 10、加入组织 11、投票 12、修改组织logo 13、增发资产
     */
    public Byte getOperationType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.additional_info</code>. 附加信息(JSON字符串)
     */
    public void setAdditionalInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.additional_info</code>. 附加信息(JSON字符串)
     */
    public String getAdditionalInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.tx_status</code>. 交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败，3-无需上链
     */
    public void setTxStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.tx_status</code>. 交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败，3-无需上链
     */
    public Byte getTxStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.operator</code>. 操作人地址
     */
    public void setOperator(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.operator</code>. 操作人地址
     */
    public String getOperator() {
        return (String) get(6);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>asimov_server.t_dao_operation.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>asimov_server.t_dao_operation.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, Byte, String, Byte, String, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, Byte, String, Byte, String, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TDaoOperation.T_DAO_OPERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TDaoOperation.T_DAO_OPERATION.TX_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TDaoOperation.T_DAO_OPERATION.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return TDaoOperation.T_DAO_OPERATION.OPERATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TDaoOperation.T_DAO_OPERATION.ADDITIONAL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TDaoOperation.T_DAO_OPERATION.TX_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TDaoOperation.T_DAO_OPERATION.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TDaoOperation.T_DAO_OPERATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TDaoOperation.T_DAO_OPERATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getOperationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getTxStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getOperationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getTxStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value2(String value) {
        setTxHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value3(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value4(Byte value) {
        setOperationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value5(String value) {
        setAdditionalInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value6(Byte value) {
        setTxStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value7(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value8(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord value9(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoOperationRecord values(Long value1, String value2, String value3, Byte value4, String value5, Byte value6, String value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TDaoOperationRecord
     */
    public TDaoOperationRecord() {
        super(TDaoOperation.T_DAO_OPERATION);
    }

    /**
     * Create a detached, initialised TDaoOperationRecord
     */
    public TDaoOperationRecord(Long id, String txHash, String contractAddress, Byte operationType, String additionalInfo, Byte txStatus, String operator, Long createTime, Long updateTime) {
        super(TDaoOperation.T_DAO_OPERATION);

        set(0, id);
        set(1, txHash);
        set(2, contractAddress);
        set(3, operationType);
        set(4, additionalInfo);
        set(5, txStatus);
        set(6, operator);
        set(7, createTime);
        set(8, updateTime);
    }
}
