/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TFoundationOperation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFoundationOperationRecord extends UpdatableRecordImpl<TFoundationOperationRecord> implements Record8<Long, String, Byte, String, Byte, String, Long, Long> {

    private static final long serialVersionUID = -337719031;

    /**
     * Setter for <code>asimov_server.t_foundation_operation.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.tx_hash</code>. 交易Hash
     */
    public void setTxHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.tx_hash</code>. 交易Hash
     */
    public String getTxHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.operation_type</code>. 操作类型：1、发起提议 2、提议投票 3、捐赠
     */
    public void setOperationType(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.operation_type</code>. 操作类型：1、发起提议 2、提议投票 3、捐赠
     */
    public Byte getOperationType() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.additional_info</code>. 附加信息(JSON字符串)
     */
    public void setAdditionalInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.additional_info</code>. 附加信息(JSON字符串)
     */
    public String getAdditionalInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.tx_status</code>. 交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败
     */
    public void setTxStatus(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.tx_status</code>. 交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败
     */
    public Byte getTxStatus() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.operator</code>. 操作人地址
     */
    public void setOperator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.operator</code>. 操作人地址
     */
    public String getOperator() {
        return (String) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>asimov_server.t_foundation_operation.update_time</code>. 更新时间
     */
    public void setUpdateTime(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>asimov_server.t_foundation_operation.update_time</code>. 更新时间
     */
    public Long getUpdateTime() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Byte, String, Byte, String, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Byte, String, Byte, String, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.TX_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.OPERATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.ADDITIONAL_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.TX_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.OPERATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TFoundationOperation.T_FOUNDATION_OPERATION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getOperationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getTxStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTxHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getOperationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAdditionalInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getTxStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOperator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value2(String value) {
        setTxHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value3(Byte value) {
        setOperationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value4(String value) {
        setAdditionalInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value5(Byte value) {
        setTxStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value6(String value) {
        setOperator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value7(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord value8(Long value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFoundationOperationRecord values(Long value1, String value2, Byte value3, String value4, Byte value5, String value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TFoundationOperationRecord
     */
    public TFoundationOperationRecord() {
        super(TFoundationOperation.T_FOUNDATION_OPERATION);
    }

    /**
     * Create a detached, initialised TFoundationOperationRecord
     */
    public TFoundationOperationRecord(Long id, String txHash, Byte operationType, String additionalInfo, Byte txStatus, String operator, Long createTime, Long updateTime) {
        super(TFoundationOperation.T_FOUNDATION_OPERATION);

        set(0, id);
        set(1, txHash);
        set(2, operationType);
        set(3, additionalInfo);
        set(4, txStatus);
        set(5, operator);
        set(6, createTime);
        set(7, updateTime);
    }
}
