/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.records;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TRollback;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRollbackRecord extends UpdatableRecordImpl<TRollbackRecord> implements Record7<Long, Long, Long, String, Byte, Byte, Long> {

    private static final long serialVersionUID = 236179746;

    /**
     * Setter for <code>asimov_server.t_rollback.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.height</code>. 块高
     */
    public void setHeight(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.height</code>. 块高
     */
    public Long getHeight() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.record_id</code>. 需要回滚的表ID
     */
    public void setRecordId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.record_id</code>. 需要回滚的表ID
     */
    public Long getRecordId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.table_name</code>. 需要回滚的表名
     */
    public void setTableName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.table_name</code>. 需要回滚的表名
     */
    public String getTableName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.original_value</code>. 原始值
     */
    public void setOriginalValue(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.original_value</code>. 原始值
     */
    public Byte getOriginalValue() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.expect_value</code>. 期望值
     */
    public void setExpectValue(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.expect_value</code>. 期望值
     */
    public Byte getExpectValue() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>asimov_server.t_rollback.create_time</code>. 创建时间
     */
    public void setCreateTime(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>asimov_server.t_rollback.create_time</code>. 创建时间
     */
    public Long getCreateTime() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, String, Byte, Byte, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, String, Byte, Byte, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TRollback.T_ROLLBACK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TRollback.T_ROLLBACK.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TRollback.T_ROLLBACK.RECORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TRollback.T_ROLLBACK.TABLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return TRollback.T_ROLLBACK.ORIGINAL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return TRollback.T_ROLLBACK.EXPECT_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TRollback.T_ROLLBACK.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getOriginalValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getExpectValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRecordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getOriginalValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getExpectValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value2(Long value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value3(Long value) {
        setRecordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value4(String value) {
        setTableName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value5(Byte value) {
        setOriginalValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value6(Byte value) {
        setExpectValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord value7(Long value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TRollbackRecord values(Long value1, Long value2, Long value3, String value4, Byte value5, Byte value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRollbackRecord
     */
    public TRollbackRecord() {
        super(TRollback.T_ROLLBACK);
    }

    /**
     * Create a detached, initialised TRollbackRecord
     */
    public TRollbackRecord(Long id, Long height, Long recordId, String tableName, Byte originalValue, Byte expectValue, Long createTime) {
        super(TRollback.T_ROLLBACK);

        set(0, id);
        set(1, height);
        set(2, recordId);
        set(3, tableName);
        set(4, originalValue);
        set(5, expectValue);
        set(6, createTime);
    }
}
