/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database;


import javax.annotation.Generated;

import network.asimov.mysql.database.tables.TChainNode;
import network.asimov.mysql.database.tables.TDaoAccount;
import network.asimov.mysql.database.tables.TDaoAsset;
import network.asimov.mysql.database.tables.TDaoIndivisibleAsset;
import network.asimov.mysql.database.tables.TDaoMessage;
import network.asimov.mysql.database.tables.TDaoOperation;
import network.asimov.mysql.database.tables.TDaoOrganization;
import network.asimov.mysql.database.tables.TFoundationOperation;
import network.asimov.mysql.database.tables.TMinerOperation;
import network.asimov.mysql.database.tables.TRollback;


/**
 * Convenience access to all tables in asimov_server
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>asimov_server.t_chain_node</code>.
     */
    public static final TChainNode T_CHAIN_NODE = network.asimov.mysql.database.tables.TChainNode.T_CHAIN_NODE;

    /**
     * The table <code>asimov_server.t_dao_account</code>.
     */
    public static final TDaoAccount T_DAO_ACCOUNT = network.asimov.mysql.database.tables.TDaoAccount.T_DAO_ACCOUNT;

    /**
     * The table <code>asimov_server.t_dao_asset</code>.
     */
    public static final TDaoAsset T_DAO_ASSET = network.asimov.mysql.database.tables.TDaoAsset.T_DAO_ASSET;

    /**
     * The table <code>asimov_server.t_dao_indivisible_asset</code>.
     */
    public static final TDaoIndivisibleAsset T_DAO_INDIVISIBLE_ASSET = network.asimov.mysql.database.tables.TDaoIndivisibleAsset.T_DAO_INDIVISIBLE_ASSET;

    /**
     * The table <code>asimov_server.t_dao_message</code>.
     */
    public static final TDaoMessage T_DAO_MESSAGE = network.asimov.mysql.database.tables.TDaoMessage.T_DAO_MESSAGE;

    /**
     * The table <code>asimov_server.t_dao_operation</code>.
     */
    public static final TDaoOperation T_DAO_OPERATION = network.asimov.mysql.database.tables.TDaoOperation.T_DAO_OPERATION;

    /**
     * The table <code>asimov_server.t_dao_organization</code>.
     */
    public static final TDaoOrganization T_DAO_ORGANIZATION = network.asimov.mysql.database.tables.TDaoOrganization.T_DAO_ORGANIZATION;

    /**
     * The table <code>asimov_server.t_foundation_operation</code>.
     */
    public static final TFoundationOperation T_FOUNDATION_OPERATION = network.asimov.mysql.database.tables.TFoundationOperation.T_FOUNDATION_OPERATION;

    /**
     * The table <code>asimov_server.t_miner_operation</code>.
     */
    public static final TMinerOperation T_MINER_OPERATION = network.asimov.mysql.database.tables.TMinerOperation.T_MINER_OPERATION;

    /**
     * The table <code>asimov_server.t_rollback</code>.
     */
    public static final TRollback T_ROLLBACK = network.asimov.mysql.database.tables.TRollback.T_ROLLBACK;
}
