/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TChainNode implements Serializable {

    private static final long serialVersionUID = 1370272641;

    private Long   id;
    private String ip;
    private String city;
    private String subdivision;
    private String country;
    private String longitude;
    private String latitude;
    private Long   createTime;
    private Long   updateTime;

    public TChainNode() {}

    public TChainNode(TChainNode value) {
        this.id = value.id;
        this.ip = value.ip;
        this.city = value.city;
        this.subdivision = value.subdivision;
        this.country = value.country;
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TChainNode(
        Long   id,
        String ip,
        String city,
        String subdivision,
        String country,
        String longitude,
        String latitude,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.ip = ip;
        this.city = city;
        this.subdivision = subdivision;
        this.country = country;
        this.longitude = longitude;
        this.latitude = latitude;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getSubdivision() {
        return this.subdivision;
    }

    public void setSubdivision(String subdivision) {
        this.subdivision = subdivision;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TChainNode (");

        sb.append(id);
        sb.append(", ").append(ip);
        sb.append(", ").append(city);
        sb.append(", ").append(subdivision);
        sb.append(", ").append(country);
        sb.append(", ").append(longitude);
        sb.append(", ").append(latitude);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
