/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoOrganization implements Serializable {

    private static final long serialVersionUID = -174795682;

    private Long   id;
    private String txHash;
    private String contractAddress;
    private String voteContractAddress;
    private String creatorAddress;
    private String orgName;
    private String orgLogo;
    private Byte   state;
    private Long   createTime;
    private Long   updateTime;

    public TDaoOrganization() {}

    public TDaoOrganization(TDaoOrganization value) {
        this.id = value.id;
        this.txHash = value.txHash;
        this.contractAddress = value.contractAddress;
        this.voteContractAddress = value.voteContractAddress;
        this.creatorAddress = value.creatorAddress;
        this.orgName = value.orgName;
        this.orgLogo = value.orgLogo;
        this.state = value.state;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoOrganization(
        Long   id,
        String txHash,
        String contractAddress,
        String voteContractAddress,
        String creatorAddress,
        String orgName,
        String orgLogo,
        Byte   state,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.txHash = txHash;
        this.contractAddress = contractAddress;
        this.voteContractAddress = voteContractAddress;
        this.creatorAddress = creatorAddress;
        this.orgName = orgName;
        this.orgLogo = orgLogo;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTxHash() {
        return this.txHash;
    }

    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    public String getContractAddress() {
        return this.contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public String getVoteContractAddress() {
        return this.voteContractAddress;
    }

    public void setVoteContractAddress(String voteContractAddress) {
        this.voteContractAddress = voteContractAddress;
    }

    public String getCreatorAddress() {
        return this.creatorAddress;
    }

    public void setCreatorAddress(String creatorAddress) {
        this.creatorAddress = creatorAddress;
    }

    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getOrgLogo() {
        return this.orgLogo;
    }

    public void setOrgLogo(String orgLogo) {
        this.orgLogo = orgLogo;
    }

    public Byte getState() {
        return this.state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoOrganization (");

        sb.append(id);
        sb.append(", ").append(txHash);
        sb.append(", ").append(contractAddress);
        sb.append(", ").append(voteContractAddress);
        sb.append(", ").append(creatorAddress);
        sb.append(", ").append(orgName);
        sb.append(", ").append(orgLogo);
        sb.append(", ").append(state);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
