/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoIndivisibleAsset implements Serializable {

    private static final long serialVersionUID = 1958285707;

    private Long   id;
    private String txHash;
    private String contractAddress;
    private String asset;
    private Long   voucherId;
    private String assetDesc;
    private Byte   assetStatus;
    private Long   createTime;
    private Long   updateTime;

    public TDaoIndivisibleAsset() {}

    public TDaoIndivisibleAsset(TDaoIndivisibleAsset value) {
        this.id = value.id;
        this.txHash = value.txHash;
        this.contractAddress = value.contractAddress;
        this.asset = value.asset;
        this.voucherId = value.voucherId;
        this.assetDesc = value.assetDesc;
        this.assetStatus = value.assetStatus;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoIndivisibleAsset(
        Long   id,
        String txHash,
        String contractAddress,
        String asset,
        Long   voucherId,
        String assetDesc,
        Byte   assetStatus,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.txHash = txHash;
        this.contractAddress = contractAddress;
        this.asset = asset;
        this.voucherId = voucherId;
        this.assetDesc = assetDesc;
        this.assetStatus = assetStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTxHash() {
        return this.txHash;
    }

    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    public String getContractAddress() {
        return this.contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public String getAsset() {
        return this.asset;
    }

    public void setAsset(String asset) {
        this.asset = asset;
    }

    public Long getVoucherId() {
        return this.voucherId;
    }

    public void setVoucherId(Long voucherId) {
        this.voucherId = voucherId;
    }

    public String getAssetDesc() {
        return this.assetDesc;
    }

    public void setAssetDesc(String assetDesc) {
        this.assetDesc = assetDesc;
    }

    public Byte getAssetStatus() {
        return this.assetStatus;
    }

    public void setAssetStatus(Byte assetStatus) {
        this.assetStatus = assetStatus;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoIndivisibleAsset (");

        sb.append(id);
        sb.append(", ").append(txHash);
        sb.append(", ").append(contractAddress);
        sb.append(", ").append(asset);
        sb.append(", ").append(voucherId);
        sb.append(", ").append(assetDesc);
        sb.append(", ").append(assetStatus);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
