/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoOperation implements Serializable {

    private static final long serialVersionUID = 2129464559;

    private Long   id;
    private String txHash;
    private String contractAddress;
    private Byte   operationType;
    private String additionalInfo;
    private Byte   txStatus;
    private String operator;
    private Long   createTime;
    private Long   updateTime;

    public TDaoOperation() {}

    public TDaoOperation(TDaoOperation value) {
        this.id = value.id;
        this.txHash = value.txHash;
        this.contractAddress = value.contractAddress;
        this.operationType = value.operationType;
        this.additionalInfo = value.additionalInfo;
        this.txStatus = value.txStatus;
        this.operator = value.operator;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoOperation(
        Long   id,
        String txHash,
        String contractAddress,
        Byte   operationType,
        String additionalInfo,
        Byte   txStatus,
        String operator,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.txHash = txHash;
        this.contractAddress = contractAddress;
        this.operationType = operationType;
        this.additionalInfo = additionalInfo;
        this.txStatus = txStatus;
        this.operator = operator;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTxHash() {
        return this.txHash;
    }

    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    public String getContractAddress() {
        return this.contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public Byte getOperationType() {
        return this.operationType;
    }

    public void setOperationType(Byte operationType) {
        this.operationType = operationType;
    }

    public String getAdditionalInfo() {
        return this.additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public Byte getTxStatus() {
        return this.txStatus;
    }

    public void setTxStatus(Byte txStatus) {
        this.txStatus = txStatus;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoOperation (");

        sb.append(id);
        sb.append(", ").append(txHash);
        sb.append(", ").append(contractAddress);
        sb.append(", ").append(operationType);
        sb.append(", ").append(additionalInfo);
        sb.append(", ").append(txStatus);
        sb.append(", ").append(operator);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
