/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoMessage implements Serializable {

    private static final long serialVersionUID = 1644835672;

    private Long    id;
    private Integer category;
    private Integer type;
    private Integer messagePosition;
    private String  contractAddress;
    private String  receiver;
    private String  additionalInfo;
    private Integer state;
    private Long    createTime;
    private Long    updateTime;

    public TDaoMessage() {}

    public TDaoMessage(TDaoMessage value) {
        this.id = value.id;
        this.category = value.category;
        this.type = value.type;
        this.messagePosition = value.messagePosition;
        this.contractAddress = value.contractAddress;
        this.receiver = value.receiver;
        this.additionalInfo = value.additionalInfo;
        this.state = value.state;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoMessage(
        Long    id,
        Integer category,
        Integer type,
        Integer messagePosition,
        String  contractAddress,
        String  receiver,
        String  additionalInfo,
        Integer state,
        Long    createTime,
        Long    updateTime
    ) {
        this.id = id;
        this.category = category;
        this.type = type;
        this.messagePosition = messagePosition;
        this.contractAddress = contractAddress;
        this.receiver = receiver;
        this.additionalInfo = additionalInfo;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCategory() {
        return this.category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getMessagePosition() {
        return this.messagePosition;
    }

    public void setMessagePosition(Integer messagePosition) {
        this.messagePosition = messagePosition;
    }

    public String getContractAddress() {
        return this.contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public String getReceiver() {
        return this.receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getAdditionalInfo() {
        return this.additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoMessage (");

        sb.append(id);
        sb.append(", ").append(category);
        sb.append(", ").append(type);
        sb.append(", ").append(messagePosition);
        sb.append(", ").append(contractAddress);
        sb.append(", ").append(receiver);
        sb.append(", ").append(additionalInfo);
        sb.append(", ").append(state);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
