/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoAsset implements Serializable {

    private static final long serialVersionUID = 30954335;

    private Long   id;
    private String txHash;
    private String contractAddress;
    private String asset;
    private String name;
    private String symbol;
    private String description;
    private String logo;
    private Byte   assetStatus;
    private Long   createTime;
    private Long   updateTime;

    public TDaoAsset() {}

    public TDaoAsset(TDaoAsset value) {
        this.id = value.id;
        this.txHash = value.txHash;
        this.contractAddress = value.contractAddress;
        this.asset = value.asset;
        this.name = value.name;
        this.symbol = value.symbol;
        this.description = value.description;
        this.logo = value.logo;
        this.assetStatus = value.assetStatus;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoAsset(
        Long   id,
        String txHash,
        String contractAddress,
        String asset,
        String name,
        String symbol,
        String description,
        String logo,
        Byte   assetStatus,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.txHash = txHash;
        this.contractAddress = contractAddress;
        this.asset = asset;
        this.name = name;
        this.symbol = symbol;
        this.description = description;
        this.logo = logo;
        this.assetStatus = assetStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTxHash() {
        return this.txHash;
    }

    public void setTxHash(String txHash) {
        this.txHash = txHash;
    }

    public String getContractAddress() {
        return this.contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    public String getAsset() {
        return this.asset;
    }

    public void setAsset(String asset) {
        this.asset = asset;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public Byte getAssetStatus() {
        return this.assetStatus;
    }

    public void setAssetStatus(Byte assetStatus) {
        this.assetStatus = assetStatus;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoAsset (");

        sb.append(id);
        sb.append(", ").append(txHash);
        sb.append(", ").append(contractAddress);
        sb.append(", ").append(asset);
        sb.append(", ").append(name);
        sb.append(", ").append(symbol);
        sb.append(", ").append(description);
        sb.append(", ").append(logo);
        sb.append(", ").append(assetStatus);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
