/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoAccount implements Serializable {

    private static final long serialVersionUID = 364084724;

    private Long   id;
    private String address;
    private String nickName;
    private String avatar;
    private Long   createTime;
    private Long   updateTime;

    public TDaoAccount() {}

    public TDaoAccount(TDaoAccount value) {
        this.id = value.id;
        this.address = value.address;
        this.nickName = value.nickName;
        this.avatar = value.avatar;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TDaoAccount(
        Long   id,
        String address,
        String nickName,
        String avatar,
        Long   createTime,
        Long   updateTime
    ) {
        this.id = id;
        this.address = address;
        this.nickName = nickName;
        this.avatar = avatar;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDaoAccount (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(nickName);
        sb.append(", ").append(avatar);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
