/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRollback implements Serializable {

    private static final long serialVersionUID = -1858701097;

    private Long   id;
    private Long   height;
    private Long   recordId;
    private String tableName;
    private Byte   originalValue;
    private Byte   expectValue;
    private Long   createTime;

    public TRollback() {}

    public TRollback(TRollback value) {
        this.id = value.id;
        this.height = value.height;
        this.recordId = value.recordId;
        this.tableName = value.tableName;
        this.originalValue = value.originalValue;
        this.expectValue = value.expectValue;
        this.createTime = value.createTime;
    }

    public TRollback(
        Long   id,
        Long   height,
        Long   recordId,
        String tableName,
        Byte   originalValue,
        Byte   expectValue,
        Long   createTime
    ) {
        this.id = id;
        this.height = height;
        this.recordId = recordId;
        this.tableName = tableName;
        this.originalValue = originalValue;
        this.expectValue = expectValue;
        this.createTime = createTime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHeight() {
        return this.height;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public Byte getOriginalValue() {
        return this.originalValue;
    }

    public void setOriginalValue(Byte originalValue) {
        this.originalValue = originalValue;
    }

    public Byte getExpectValue() {
        return this.expectValue;
    }

    public void setExpectValue(Byte expectValue) {
        this.expectValue = expectValue;
    }

    public Long getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRollback (");

        sb.append(id);
        sb.append(", ").append(height);
        sb.append(", ").append(recordId);
        sb.append(", ").append(tableName);
        sb.append(", ").append(originalValue);
        sb.append(", ").append(expectValue);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
