/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import network.asimov.mysql.database.AsimovServer;
import network.asimov.mysql.database.Indexes;
import network.asimov.mysql.database.Keys;
import network.asimov.mysql.database.tables.records.TDaoAssetRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDaoAsset extends TableImpl<TDaoAssetRecord> {

    private static final long serialVersionUID = -820209160;

    /**
     * The reference instance of <code>asimov_server.t_dao_asset</code>
     */
    public static final TDaoAsset T_DAO_ASSET = new TDaoAsset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDaoAssetRecord> getRecordType() {
        return TDaoAssetRecord.class;
    }

    /**
     * The column <code>asimov_server.t_dao_asset.id</code>. 主键
     */
    public final TableField<TDaoAssetRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>asimov_server.t_dao_asset.tx_hash</code>. 交易Hash
     */
    public final TableField<TDaoAssetRecord, String> TX_HASH = createField("tx_hash", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "交易Hash");

    /**
     * The column <code>asimov_server.t_dao_asset.contract_address</code>. 组织合约地址
     */
    public final TableField<TDaoAssetRecord, String> CONTRACT_ADDRESS = createField("contract_address", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "组织合约地址");

    /**
     * The column <code>asimov_server.t_dao_asset.asset</code>. 资产ID
     */
    public final TableField<TDaoAssetRecord, String> ASSET = createField("asset", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "资产ID");

    /**
     * The column <code>asimov_server.t_dao_asset.name</code>. 资产名称
     */
    public final TableField<TDaoAssetRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "资产名称");

    /**
     * The column <code>asimov_server.t_dao_asset.symbol</code>. 资产symbol
     */
    public final TableField<TDaoAssetRecord, String> SYMBOL = createField("symbol", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "资产symbol");

    /**
     * The column <code>asimov_server.t_dao_asset.description</code>. 资产描述
     */
    public final TableField<TDaoAssetRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "资产描述");

    /**
     * The column <code>asimov_server.t_dao_asset.logo</code>. 资产logo
     */
    public final TableField<TDaoAssetRecord, String> LOGO = createField("logo", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "资产logo");

    /**
     * The column <code>asimov_server.t_dao_asset.asset_status</code>. 资产状态，0-初始化，待投票通过，1-发行成功，2-发行失败
     */
    public final TableField<TDaoAssetRecord, Byte> ASSET_STATUS = createField("asset_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "资产状态，0-初始化，待投票通过，1-发行成功，2-发行失败");

    /**
     * The column <code>asimov_server.t_dao_asset.create_time</code>. 创建时间
     */
    public final TableField<TDaoAssetRecord, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "创建时间");

    /**
     * The column <code>asimov_server.t_dao_asset.update_time</code>. 更新时间
     */
    public final TableField<TDaoAssetRecord, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "更新时间");

    /**
     * Create a <code>asimov_server.t_dao_asset</code> table reference
     */
    public TDaoAsset() {
        this(DSL.name("t_dao_asset"), null);
    }

    /**
     * Create an aliased <code>asimov_server.t_dao_asset</code> table reference
     */
    public TDaoAsset(String alias) {
        this(DSL.name(alias), T_DAO_ASSET);
    }

    /**
     * Create an aliased <code>asimov_server.t_dao_asset</code> table reference
     */
    public TDaoAsset(Name alias) {
        this(alias, T_DAO_ASSET);
    }

    private TDaoAsset(Name alias, Table<TDaoAssetRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDaoAsset(Name alias, Table<TDaoAssetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TDaoAsset(Table<O> child, ForeignKey<O, TDaoAssetRecord> key) {
        super(child, key, T_DAO_ASSET);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AsimovServer.ASIMOV_SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_DAO_ASSET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDaoAssetRecord> getPrimaryKey() {
        return Keys.KEY_T_DAO_ASSET_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDaoAssetRecord>> getKeys() {
        return Arrays.<UniqueKey<TDaoAssetRecord>>asList(Keys.KEY_T_DAO_ASSET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAsset as(String alias) {
        return new TDaoAsset(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDaoAsset as(Name alias) {
        return new TDaoAsset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDaoAsset rename(String name) {
        return new TDaoAsset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TDaoAsset rename(Name name) {
        return new TDaoAsset(name, null);
    }
}
