/*
 * This file is generated by jOOQ.
 */
package network.asimov.mysql.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import network.asimov.mysql.database.AsimovServer;
import network.asimov.mysql.database.Indexes;
import network.asimov.mysql.database.Keys;
import network.asimov.mysql.database.tables.records.TMinerOperationRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMinerOperation extends TableImpl<TMinerOperationRecord> {

    private static final long serialVersionUID = -438176792;

    /**
     * The reference instance of <code>asimov_server.t_miner_operation</code>
     */
    public static final TMinerOperation T_MINER_OPERATION = new TMinerOperation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMinerOperationRecord> getRecordType() {
        return TMinerOperationRecord.class;
    }

    /**
     * The column <code>asimov_server.t_miner_operation.id</code>. 主键
     */
    public final TableField<TMinerOperationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>asimov_server.t_miner_operation.tx_hash</code>. 交易Hash
     */
    public final TableField<TMinerOperationRecord, String> TX_HASH = createField("tx_hash", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "交易Hash");

    /**
     * The column <code>asimov_server.t_miner_operation.operation_type</code>. 操作类型：1、提议 2、报名 3、投票
     */
    public final TableField<TMinerOperationRecord, Byte> OPERATION_TYPE = createField("operation_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "操作类型：1、提议 2、报名 3、投票");

    /**
     * The column <code>asimov_server.t_miner_operation.round</code>. 轮次
     */
    public final TableField<TMinerOperationRecord, Long> ROUND = createField("round", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "轮次");

    /**
     * The column <code>asimov_server.t_miner_operation.additional_info</code>. 附加信息(JSON字符串)
     */
    public final TableField<TMinerOperationRecord, String> ADDITIONAL_INFO = createField("additional_info", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "附加信息(JSON字符串)");

    /**
     * The column <code>asimov_server.t_miner_operation.tx_status</code>. 交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败
     */
    public final TableField<TMinerOperationRecord, Byte> TX_STATUS = createField("tx_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "交易状态，0-待确认，1-交易入块、合约执行成功，2-交易入块、合约执行失败");

    /**
     * The column <code>asimov_server.t_miner_operation.operator</code>. 操作人地址
     */
    public final TableField<TMinerOperationRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "操作人地址");

    /**
     * The column <code>asimov_server.t_miner_operation.create_time</code>. 创建时间
     */
    public final TableField<TMinerOperationRecord, Long> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "创建时间");

    /**
     * The column <code>asimov_server.t_miner_operation.update_time</code>. 更新时间
     */
    public final TableField<TMinerOperationRecord, Long> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "更新时间");

    /**
     * Create a <code>asimov_server.t_miner_operation</code> table reference
     */
    public TMinerOperation() {
        this(DSL.name("t_miner_operation"), null);
    }

    /**
     * Create an aliased <code>asimov_server.t_miner_operation</code> table reference
     */
    public TMinerOperation(String alias) {
        this(DSL.name(alias), T_MINER_OPERATION);
    }

    /**
     * Create an aliased <code>asimov_server.t_miner_operation</code> table reference
     */
    public TMinerOperation(Name alias) {
        this(alias, T_MINER_OPERATION);
    }

    private TMinerOperation(Name alias, Table<TMinerOperationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMinerOperation(Name alias, Table<TMinerOperationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TMinerOperation(Table<O> child, ForeignKey<O, TMinerOperationRecord> key) {
        super(child, key, T_MINER_OPERATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AsimovServer.ASIMOV_SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_MINER_OPERATION_INDEX_OPERATION_TYPE, Indexes.T_MINER_OPERATION_INDEX_OPERATOR_TYPE, Indexes.T_MINER_OPERATION_INDEX_ROUND_OPERATOR_TYPE, Indexes.T_MINER_OPERATION_INDEX_TX_HASH_UNIQUE, Indexes.T_MINER_OPERATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TMinerOperationRecord> getPrimaryKey() {
        return Keys.KEY_T_MINER_OPERATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TMinerOperationRecord>> getKeys() {
        return Arrays.<UniqueKey<TMinerOperationRecord>>asList(Keys.KEY_T_MINER_OPERATION_PRIMARY, Keys.KEY_T_MINER_OPERATION_INDEX_TX_HASH_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMinerOperation as(String alias) {
        return new TMinerOperation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMinerOperation as(Name alias) {
        return new TMinerOperation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMinerOperation rename(String name) {
        return new TMinerOperation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMinerOperation rename(Name name) {
        return new TMinerOperation(name, null);
    }
}
